### ISSUE TITLE
cwl-tes for cwl input testing

### ISSUE THREAD

**Issue by erikvdbergh** [EMBL-EBI-TSI/TESK#47] opened 2018-04-23 10:55 UTC
A fork of cwl-tes has been created to facilitate cwl input to TESK. Needed for User Story 1 (#6). Remote file functionality will need to be implemented in cwl-tes to make it work with k8s.

fork: https://github.com/erikvdbergh/cwl-tes

**Comment by susheel** [comment] 2018-05-18 08:29
Duplicate of #34

**Closed by susheel** 2018-05-18 08:29 UTC
